[project]
name = "feed_aggregator"
version = "0.1.0"
requires-python = ">=3.9,<4"
dependencies = [
    "feedparser>=6.0.10",
    "feedgen>=0.9.0",
    "pydantic[email]>=2.5.2",
    "httpx>=0.25.2",
]

[tool.pdm.dev-dependencies]
dev = ["pytest>=7.4.3"]
